// Incoming events
export const ERROR_EVENT = 'error'
export const STATE_EVENT = 'state'
export const WORLD_EVENT = 'world'
export const WORLDS_EVENT = 'worlds'
export const ADMINS_EVENT = 'admins'
export const BANNED_EVENT = 'banned'
export const PERMITTED_EVENT = 'permitted'
export const PERF_EVENT = 'perf'
export const OUTPUT_EVENT = 'output'

// Outgoing events
export const AUTH_EVENT = 'auth'
export const SERVER_START_EVENT = 'server.start'
export const SERVER_STOP_EVENT = 'server.stop'
export const WORLD_GET_EVENT = 'world.get'
export const WORLD_ADD_EVENT = 'world.add'
export const WORLDS_DELETE_EVENT = 'worlds.delete'
export const ADMIN_ADD_EVENT = 'admin.add'
export const ADMINS_DELETE_EVENT = 'admins.delete'
export const BANNED_ADD_EVENT = 'banned.add'
export const BANNED_DELETE_EVENT = 'banned.delete'
export const PERMITTED_ADD_EVENT = 'permitted.add'
export const PERMITTED_DELETE_EVENT = 'permitted.delete'
